/**
 * constant string file
 */
export const InputLabel = {
  email: 'Email',
  password: 'Password',
  flat: 'Flat,House no,Bulding,Company,Apartment',
  city: 'City',
  state: 'State',
  pincode: 'Pincode',
  firstname: 'First Name',
  lastname: 'Last Name',
  conformPass: 'Conform Password',
};

export const PlaceHolder = {
  email: 'Email',
  password: 'Password',
  firstname: 'First Name',
  lastname: 'Last Name',
  conformPass: 'Conform Password',
};

export const ButtonLabel = {
  submit: 'Submit',
  addtocart: 'Add To Cart',
  home: 'Home',
  profile: 'Profile',
  signOut: 'Sign Out',
  login: 'Login',
  security: 'Security',
  edit: 'Edit',
  buyNow: 'Buy Now',
  placeOrder: 'Place Order',
  delete: 'Delete',
  cancel: 'Cancel',
  goToHome: 'Shop Now',
  cart: 'Cart',
  registerNow: ' Register Now',
  register: 'Register',
  refresh: 'Refresh',
  ok: 'Ok',
  remove: 'Remove',
  order: 'Order',
  gotoShopping: 'Go To Shopping',
};

export const CommonStrings = {
  productName: 'One Plus Ear Buds',
  availabel: 'Availabel',
  hello: 'Hello!',
  myCart: 'My Cart',
  orderInfo: 'Order Info',
  total: 'Total',
  category: 'Category',
  products: 'Products',
  shopping: 'Shopping',
  description:
    'Up to 20 hours battery life | Super powerful Bass | 40mm dynamic driver | Pressure less ear muffs | Bluetooth 5.0 | Voice control',
  profileScreen: 'ProfileScreen',
  phone: 'Phone',
  cradencialNotMatch: 'Your Cradencial dose not match',
  noItemInCart: 'there is no item in cart',
  deliveryLocation: 'Delivery Location',
  flat: 'B-105, Apple Residency',
  paymentMethod: 'Payment Method',
  visaClassic: 'Visa Classic',
  cardNumber: '****-9092',
  changeCredential: 'Change Credential',
  signUp: 'Sign Up',
  areYouSure: 'Are You sure?',
  alertMessage: 'This is item delete permanently from cart',
  city: 'Ahmedabad',
  state: 'Gujrat',
  pincode: '382350',
  visa: 'VISA',
  total: 'Total',
  noCategory: 'No category Please wait for some time',
  noProduct: ' No Product Found',
  orderWill: 'Order Will be Deliver Soon',
  orderDetail: 'Order Detail',
  productDetail: 'Product Details',
  qty: 'Qty',
  discount: 'Discount',
  freeDelivery: 'Free Delivery',
  flatTwo: 'Rustaveli Ave 57',
  cityTwo: '17-001, Batume',
  headQuater: 'Head Quater',
  appName: 'Any Buy',
  dataSubmit: 'Your Data is submitted',
  token: 'dfsudgfi',
  loading: 'Loading...',
  addFlag: 'add',
  orLoginWith: 'Or Login With',
  welcome: 'Welcome back! Glad to see you, Again!',
  notRegister: `Don't have an account?`,
  alreadyRegister: 'Already have an account?',
  forgetPassword: 'Forget Password?',
  email: 'eve.holt@reqres.in',
  password: 'pistol',
  loginNow: ' Login Now',
  first_name: 'Senorita',
  last_name: 'Avarop',
  noMoreUser: 'No more Users at the moment',
  noData: 'No Data at the moment',
  user: 'Users',
  hellomsj: 'Hello! Register to get started',
  userDetail: 'User Detail',
  noCategory: 'No category found',
  rupee: `₹`,
  noAccount: 'Email id is not registerd',
  wrongPasseord: 'Please enter correct password',
  cart: 'cart',
  allToken: 'cat_dusdhususuwj',
  search: 'Search...',
  orderId: 'Order Id',
  status: 'Status',
  productId: 'product_id',
  all: 'All',
  avoidP: /<[^>]+>/g,
  offer: 'Offer',
  testGateWay: 'test_gateway',
  cardNumber: '4242 4242 4242 4242',
  postalZipcode: '94107',
  orderMessage: `Your Payment is completed. 
  Please check your order status at 
  Order Page`,
};

export const YupErrorMessage = {
  require: 'this feild is required',
  nameError: 'name should have min 2 and max 30 character',
  emailError: 'please enter valid email',
  passwordError: 'password shoud have minimum 7 character',
  cityError: 'city name should be min 30 character',
  stateError: 'state name should be min 30 character',
  pincodeError: 'lease enter valid pincode(123456)',
};

export const Route = {
  login: 'LoginScreen',
  signup: 'SignupScreen',
  drawerRoute: 'DrawerRoute',
  bottomtabRoute: 'BottomTabRoute',
  homeScreen: 'HomeScreen',
  cartScreen: 'CartScreen',
  productInfoRoute: 'ProductInfoRoute',
  profileRoute: 'ProfileRoute',
  productListScreen: 'ProductListScreen',
  editAuth: 'EditAuth',
  orderScreen: 'OrderScreen',
  deliverOrder: 'DeliverOrder',
  orderPlaced: 'OrderPlaced',
};

export const reducerName = {
  authReducer: 'AuthReducer',
  cartReducer: 'CartReducer',
  categoryReducer: 'CategoryReducer',
  orderReducer: 'OrderReducer',
  productReducer: 'ProductReducer',
};

export const apiUrl = {
  baseUrl: 'https://api.chec.io/v1',
  header: {
    'Content-Type': 'application/json',
    'X-Authorization': 'sk_523883b740e182c86db2aa966e4b7f09a159571702b64',
  },
  customers: '/customers',
  carts: '/carts',
  categories: '/categories',
  orders: '/orders',
  checkouts: '/checkouts/',
  products: '/products',
  items: '/items',
};

export const reducerActions = {
  signUp: 'AuthReducer/signUp',
  login: 'AuthReducer/login',
  customerUpdate: 'AuthReducer/customerUpdate',
  createCart: 'CartReducer/createCart',
  getCarts: 'CartReducer/getCarts',
  addToCart: 'CartReducer/addToCart',
  getCategory: 'CategoryReducer/getCategory',
  orderList: 'OrderReducer/orderList',
  generateCheckout: 'OrderReducer/generateCheckout',
  getProducts: 'ProductReducer/getProducts',
  checkoutProducts: 'ProductReducer/checkoutProducts',
  removeItem: 'CartReducer/removeItem',
};
